### ISSUE TITLE
Rest API record/live Last Inverter parts missing[Bug]

### ISSUE THREAD

**Issue by Joggi87** [lumapu/ahoy#1086]
### Platform

ESP32

### Assembly

the DTU was already assembled

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.7.6

### Github Hash

cbdb15050f8d0ff619af2ce16918dffc26aa76d8

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Everything is running on web interface but on rest api some data is missing

### Error description

If I added four Inverters to the Ahoy DTU an read the data by Rest API record/live all Inverters where showen, but on the last Inverter some Data is missing. On the Ahoy DTU Web interface all inverters are visable and all the data is present.

![Ahoy DTU Bug](https://github.com/lumapu/ahoy/assets/51816193/839a6ef8-5f35-4a6d-9409-35021d1a80d3)

**Comment by MetaChuh** [comment]
@Joggi87 
this is not a bug, this is due to the missing memory to create a huge list for multiple inverters and panel channels.

you have to query `http://$dtu_ip/api/live` to get the list and activeness of all inverters.
then use `http://$dtu_ip/api/inverter/id/$inverter_key` for each inverter, one by one.

this has been documented and explained by @lumapu within one of the issue tickets.

greetings,
metachuh
