### ISSUE TITLE
Funkmodul CMT2300A: Kann man damit HMS- und HM-Inverter auslesen?

### ISSUE THREAD

**Issue by kiu77** [lumapu/ahoy#1466]
Die eigentliche Frage ist:
Kann das Modul CMT2300A nicht nur die neuen HMS-Typen, sondern auch noch die alten HM-Typen auslesen?
Und geht das auch gemischt? Also 1 DTU mit CMT2300A für z.B. 1x HM-800 und 1x HMS-800 gleichzeitig?
Rein technisch kann das Modul  ja einen enormen Frequenzbereich abdecken, oder gibt es da Ausführungen für spezielle Bänder, also 433, 848 MHz etc.?
Hat das schon mal jemand ausprobiert?

**Comment by kiu77** [comment]
Meine Suche führt zu folgenden Resultaten:
1. Für HM-Inverter braucht es ein NRF24L+ und für HMS-Inverter ein CMT2300A (und zwar eins fürs 868-MHz-Band).
2. Man kann beide Funkmodule an einen ESP anschließen, wobei dann klar ein ESP32 genutzt werden muss.
3. Bei einer DTU aus ESP32 und beiden Funkmodulen kann man mehrere Inverter der HM- und HMS-Serien gemischt betreiben und auslesen.

Richtig?

**Comment by Peertje-62** [comment]
Yes, 
https://github.com/tbnobody/OpenDTU
regards

**Comment by Peertje-62** [comment]
look at:
https://3printd-solution.eu/Ahoy-openDTU-Fusion-fuer-HM-HMS-HMT-mit-Display

**Comment by lumapu** [comment]
@kiu77 gute Idee nur ein Funktmodul zu nutzen, aber:
* HM / MI benötigt 2.4 GHz
* HMS / HMT benötigen 868MHz

Das CMT Funkmodul kann nur den Frequenzbereich von 140 - 1020MHz abdecken und daher nicht für beide einsetzbar. Beim NRF24 bin ich mir nicht sicher, aber vermute ähliches nur im höheren Frequenzbereich.
Unabhängig davon muss man auch alles was außenrum noch gesendet wird (das seht ihr nicht) richtig konfiguriert werden. Die Rede ist hier von Präamble, Sync, CRC, ...

Wie du schon richtig sagst unterstüzt Ahoy beim ESP32 bereits beide Module parallel, das wird wohl auch so bleiben.

@Peertje-62 Please delete your first comment because it's simply nonsens to have a link to OpenDTU without having any additional info! The second one is better.

**Comment by Peertje-62** [comment]
Dear Lumapu,
Did that but I don't agree, in the link was an list with inverters and radio modules
![List Inverter](https://github.com/lumapu/ahoy/assets/144957788/ba0a120b-447f-4405-883a-b818968fbd85)

**Comment by kiu77** [comment]
Thank you both. All clear now to me.

**Comment by lumapu** [comment]
Thank you. Next time point that out, I didn't get the message to look for a table of inverters. In general I think it doesn't fit to the question. He asked if the radios can be combined to only use one of them for all generations of Hoymiles inverters.

**Comment by Peertje-62** [comment]
Hi, 
You are right and I appreciate the work and energy you put into this project and I am still learning every day.
regards

**Comment by lumapu** [comment]
Thank you. I appreciate the team work here and in Discord. It's so great that mostly every question has an answer within the first hour. (even in night time CET) 😊

**Comment by Peertje-62** [comment]
Hi kiu77,
If your problems are solved you could /should close this issue
have a nice day
regards

**Comment by kiu77** [comment]
It's partially solved.
lumapu did read it (thanks) so we can hope ;-)

**Comment by lumapu** [comment]
will be closed with next release
