### ISSUE TITLE
[Bug] 0.8.98 and later crashes on ESP32

### ISSUE THREAD

**Issue by tavoc** [lumapu/ahoy#1545]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus, square dot

### Antenna

external antenna

### Power Stabilization

Elko (~100uF)

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.8.97

### Github Hash

GIT SHA: 9971ed7 :: 0.8.97

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

Matt every 5 seconds

### Error description

Every Version after 0.8.97 crashes on ESP32 after a few hours. Last good Version with a uptime above 12hours is 0.8.97

0.8.99- 0.8.101  are not reachable after 1-4 hours. 
Sadly I do not have a debug log

An esp8266 runs happily with all versions up to 101

Therefore it looks esp32 specific (reflashed a few times)

**Comment by rmayergfx** [comment]
Did you try another powersupply also? Is there any script running to change output (zero config?)
i am on 101 now since it was released and hat no issues so far on ESP32.

**Comment by tavoc** [comment]
I die not try yet another supply, but it was stable before and is with the 0.8.98 for days. 
No scripts are running. 

All versions before are running fine

**Comment by lumapu** [comment]
I will do a long time test here with an ESP32. So far I didn't see any problem here.

**Comment by MetaChuh** [comment]
hi @tavoc 

info: also here at my place no reboots, and a consecutive uptime of 4 days 11h since installing it using 5 inverters with 11 channels and extensive api test usage.

(unfortunately it's not going to be a higher consecutive uptime possible on this esp32, as i'm about to flash 0.8.102)

<img width="292" alt="Bildschirmfoto 2024-04-01 um 19 11 17" src="https://github.com/lumapu/ahoy/assets/45773305/2adc5e3a-470f-46d5-9dac-2719cfa9bda3">

greetings

**Comment by tavoc** [comment]
Version 102 runs now for over 18 hours. 98-101 only did up to 4.
I did not change any cabling, power supply ...

I will close this ticket.

**Comment by tavoc** [comment]
see above
