### ISSUE TITLE
YieldDay und YieldTotal Werte

### ISSUE THREAD

**Issue by Matze7779** [lumapu/ahoy#580]
Hallo,

eine Frage zu den Werten:

Sind diese DC oder AC? Also Brutto oder Netto?
Die Summe der Werte aus den blauen ist gleich des Wertes im grünen Feld.

Hintergrund der Frage: Wenn dies die DC Werte sind muss man die Wandlerverluste mit beachten bei der Auswertung / Weiterverarbeitung der Daten.

Hier noch nen Screenshot zum Verständnis was ich meine:

27+27+35+32 = 121Wh

Da oben nur die Summe angezeigt wird tentiere ich dazu das es die DC Werte sind.

Viele Grüße!

![image](https://user-images.githubusercontent.com/111183283/212044441-a9858e61-77c3-4850-ad01-7071ea920f91.png)

**Comment by Matze7779** [comment]
Habs gefunden. Ist DC.

Wer lesen kann....

https://github.com/lumapu/ahoy/blob/main/User_Manual.md

**Comment by DennisXK** [comment]
Ich verstehe das in dem Manual anderst, also YieldDay und YielTotal sind AC Werte. Macht ja eig. keinen Sinn DC Werte anzugeben, da es für die Weiterverarbeitung umständlich und nicht praktikabel ist!

**Comment by lumapu** [comment]
Da die Werte von den Invertereingängen kommen, gehe ich davon aus dass es ein DC Wert ist. Der Wert im grünen Feld wird durch einfache Summe der Einzelwerte berechnet:

https://github.com/lumapu/ahoy/blob/main/src/hm/hmDefines.h#L216

**Comment by DennisXK** [comment]
Ist das bei der originalen DTU auch so, dass die DC-Werte ausgegeben werden? Denn es macht ja kein Sinn dem Benutzer einen DC kwh Wert anzuzeigen, da der Strom da der Strom der er verbraucht bzw. den er durch die anschaffung einer Solaranlage minimiren will mit AC kwh läuft.

**Comment by lumapu** [comment]
YieldTotal kommt direkt vom Wechselrichter, ich kann meine Datenbank mal befragen, ob die täglichen Differenzen von YieldTotal der YieldDay entsprechen.
Ich kann mir gut vorstellen, dass beide Werte DC sind. Ich hoffe wir können es klären und dokumentieren.

**Comment by stefan123t** [comment]
@lumapu homeautomation hatte dazu bereits einiges gemessen, berechnet und im Discord bzw. UserManual.md beschrieben.
Wollt ihr denn ggf. ein _DC Postfix um es für die Zukunft klar zu stellen ?

Topic | Example Value | Remarks
-- | -- | --
U_AC | 233.300 | actual AC Voltage in Volt
I_AC | 0.300 | actual AC Current in Ampere
P_AC | 71.000 | actual AC Power in Watt
Q_AC | 21.200 | actual AC reactive power in var
F_AC | 49.990 | actual AC Frequency in Hz
PF_AC | 95.800 | actual AC Power factor
Temp | 19.800 | Temperature of inverter in Celsius
EVT | 9.000 | Last Event/Alarm Message Index
**YieldDay** | 51.000 | Energy converted to AC per day in Watt hours (**measured on DC**)
**YieldTotal** | 465.294 | Energy converted to AC since reset Watt hours (**measured on DC**)
P_DC | 74.600 | actual DC Power in Watt
Efficiency | 95.174 | actual ration AC Power over DC Power in percent
FWVersion | 10012.000 | Firmware version eg. 1.00.12
FWBuildYear | 2020.000 | Firmware build date
FWBuildMonthDay | 624.000 | Firmware build month and day eg. 24th of june
HWPartId | 100.000 | Hardware Id
PowerLimit | 80.000 | actual set point for power limit control AC active power in percent
LastAlarmCode | 1.000 | Last Alarm Code eg. "inverter start"
