### ISSUE TITLE
Feature Suggestion: Offline (AP-Only) mode

### ISSUE THREAD

**Issue by martin-krieger** [lumapu/ahoy#951]
Ich fände einen Offline (AP-Only) Modus wünschenswert. Bei Aktivierung dieses Modus sollte:

- Kein Versuch der Verbindung zu einem WLAN unternommen werden. MQTT ist dann ebenfalls überflüssig.
- Das Passwort für den AP ist einstellbar.
- Die Zeit wird ohne Rückfrage vom Browser übernommen. Auch wenn direkt die Live oder eine andere Unterseite aufgerufen wird.
- Falls technisch vertretbar (wozu braucht der Wechselrichter die Zeit?) wird auch ohne Zeit der Wechselrichter abgefragt und die Werte im Display angezeigt.

**Comment by tqma1** [comment]
Siehe auch: [https://github.com/lumapu/ahoy/issues](946)

**Comment by CodeFinder2** [comment]
I would also love to see this feature. Currently having difficulties to connect my AhoyDTU to inverter and wifi at the same time (both being too far apart) and would like to have the possibility to see the current status/yield when just connected to the AhoyDTU device as a compromise.

**Comment by lumapu** [comment]
ich habe es nicht ganz wie vorgeschlagen umgesetzt, tut dem aber glaube ich keinen Abbruch.

* es gibt eine Option, dass Ahoy auch ohne Zeitserver (und dessen Sync) arbeitet. Ruft man die Index Seite von Ahoy auf, wird dann automatisch die Zeit mit dem Browser synchronisiert
* das Passwort des AP ist jetzt einstellbar - das war schon lange überfällig
* MqTT ist inaktiv, wenn kein Broker gesetzt ist - war schon immer so
* es wird weiterhin versucht mit einem "Station" Wifi Verbindung aufzubauen - ich glaube das stört aber nicht weiter

bitte testen und Feedback geben - ich habe selbst dieses Setup bei mir nicht laufen 😃

**Comment by CodeFinder2** [comment]
Really appreciate your work (I prefer to respond in English so that more people can follow).

I managed to switch to an ESP32 with an external WiFi antenna and that allows me to connect to both, somehow obviating the need for this feature. Generally, I don't know why people suggest to use the old ESP8266 here. I also started with it but that was a complete mess in terms of stability. And given the minor price difference, I'd say go for the ESP32 right away.

That being said, I assume that stability issues also arise from reconnects and issues with reception and transimission to/from the inverter. My previous ESP8266 had frequent reboots and I assume that was also caused due to connection instabilities.

I am adding this here because you've written that it still tries to connect to a WiFi station/router. I'd say this should be configurable (disabled on default?) and might even be a downside in case the connection is possible from time to time. You never really know in which Wifi your AhoyDTU is currently connected, too. And in case of older ESPs (but maybe even for the ESP32), such reconnects may cause instabilities.

When I have time, I will definitely test your update (e.g., with my old ESP8266 still lying around). Thank you very much for (all!) your efforts here! :-)
