### ISSUE TITLE
/api/record/live not showing every inverter although /api/inverter/list does

### ISSUE THREAD

**Issue by fummmmel** [lumapu/ahoy#993]
### Platform

ESP32

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

circuit board

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT installed
Display installed
Added 4 Inverters
Sunrise&Sunset enabled
Inverter Poll interval 5s
Max retry 0

### Error description

Hi guys,

I was trying to get the HoyMilesZeroExport Script up and running which relies on AHOY-DTU API Data.
The Script is failing because it is missing the fourth inverter under /api/record/live:
![image](https://github.com/lumapu/ahoy/assets/93679520/21cf14ba-40b5-4f71-be3d-bc9a0a427647)
The inverter is in the inverter list under /api/inverter/list 
![image](https://github.com/lumapu/ahoy/assets/93679520/97d7bd5e-817f-47cf-b1fc-1b614ad6ea42)
All four Inverters are availlable in the UI and on MQTT. 

Any idea why it is missing on the live endpoint?
Thank you!

**Comment by fummmmel** [comment]
[ahoy.txt](https://github.com/lumapu/ahoy/files/11757254/ahoy.txt)
This is my config, I xxxed names and values.

**Comment by lumapu** [comment]
I think the problem is the entire size of the payload. In my case with 2 HMS inverters the payload is `3074` bytes long. Due to  limited memory ressources it is not possible to allocate that much memory. 
For the same reason I refactored some time ago the live view. First the endpoint `/api/live` is read and the boolean array `[iv]` is checked for enabled inverters (`true`). In a second stage an iteration over all enabled inverters occurs and the endpoint `/api/inverter/id/0` where the last digit is the id of the inverter - in your case `0 .. 1`.
The endpoint `/api/record/live` was more built as an debug purpose - maybe I have to think to remove it completely.

I'd would recommend to rewrite the mentioned script to fit to the most current API.

**Comment by reserve85** [comment]
Thank you, i´ll update the script to fit this. Thanks for clarify.

**Comment by fummmmel** [comment]
Thank you @reserve85, it's working fine now. All Inverters are found and can be controlled by the script:
![image](https://github.com/lumapu/ahoy/assets/93679520/614e9bc0-6e35-49fa-abab-e70029f23467)

**Comment by lumapu** [comment]
it should now scale to infinity number of inverters 😄
Really cool that you adjusted that fast

**Comment by reserve85** [comment]
@lumapu i would suggest to remove the endpoint /api/record/live in the upcoming versions so everyone have to implement the proofed api and will not run into the same problem. Just my opinion. Thank you for the fast help.

**Comment by ncqgm** [comment]
maybe return "deprecated" from this endpoint for a while ... ;-)
